# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('link', models.CharField(max_length=200, verbose_name='Link')),
                ('imagem', models.ImageField(null=True, upload_to='', verbose_name='imagem')),
            ],
            options={
                'verbose_name': 'portfólio',
                'verbose_name_plural': 'portfólios',
            },
        ),
    ]
